import { useEffect } from 'react';
import { Link } from 'react-router-dom';

function setMetaTag(property: string, content: string) {
  const selector = `meta[property="${property}"], meta[name="${property}"]`;
  let el = document.querySelector<HTMLMetaElement>(selector);
  if (!el) {
    el = document.createElement('meta');
    if (property.startsWith('og:') || property.startsWith('fb:')) {
      el.setAttribute('property', property);
    } else {
      el.setAttribute('name', property);
    }
    document.head.appendChild(el);
  }
  el.setAttribute('content', content);
}

export default function PrivacyPage() {
  useEffect(() => {
    const prevTitle = document.title;
    document.title = 'Privacy Policy | MCPLens';
    setMetaTag('og:title', 'Privacy Policy | MCPLens');
    setMetaTag('og:description', 'Privacy Policy for MCPLens, the AI agent readiness scanner for Shopify stores.');
    setMetaTag('og:type', 'website');
    setMetaTag('twitter:card', 'summary');

    return () => {
      document.title = prevTitle;
    };
  }, []);

  return (
    <div className="min-h-screen bg-slate-50 text-slate-700">
      {/* Nav */}
      <header className="border-b border-slate-200 px-6 py-4 bg-white/80 backdrop-blur-lg">
        <div className="max-w-3xl mx-auto flex items-center justify-between">
          <Link to="/" className="flex items-center gap-2">
            <div className="w-8 h-8 rounded-lg bg-gradient-to-br from-blue-400 to-blue-600 flex items-center justify-center">
              <span className="text-white font-bold text-sm">ML</span>
            </div>
            <span className="font-semibold text-slate-900 text-lg">MCPLens</span>
          </Link>
          <Link to="/" className="text-sm text-slate-500 hover:text-slate-900 transition-colors">
            Back to Home
          </Link>
        </div>
      </header>

      <main className="max-w-3xl mx-auto px-4 py-12">
        <div className="bg-white border border-slate-200 rounded-2xl shadow-sm p-8 sm:p-12">
          <h1 className="text-3xl font-bold text-slate-900 mb-2">Privacy Policy</h1>
          <p className="text-sm text-slate-500 mb-8">Last updated: March 24, 2026</p>

          <div className="prose prose-slate max-w-none space-y-6 text-slate-600 leading-relaxed">
            <section>
              <h2 className="text-xl font-semibold text-slate-900 mt-8 mb-3">1. What Data We Collect</h2>
              <p>We collect the following types of data:</p>
              <ul className="list-disc pl-6 space-y-1 mt-2">
                <li><strong>Email address</strong> -- provided when you create an account or unlock fix instructions for a scan result.</li>
                <li><strong>Scan results</strong> -- domain names, scores, category breakdowns, and findings generated by scanning public MCP endpoints. This includes product catalog data (names, descriptions, prices, attributes) retrieved during scans.</li>
                <li><strong>AI-generated analysis</strong> -- quality assessments and simulated buyer agent transcripts produced by third-party AI services (Google Gemini) based on product catalog data.</li>
                <li><strong>Payment information</strong> -- processed and stored by Stripe. We do not store credit card numbers or bank account details on our servers.</li>
                <li><strong>Usage data</strong> -- pages visited, scans performed, and feature usage for improving the Service.</li>
              </ul>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-slate-900 mt-8 mb-3">2. How We Use Your Data</h2>
              <ul className="list-disc pl-6 space-y-1 mt-2">
                <li><strong>Provide the Service</strong> -- generate and display scan results, track store scores over time, and deliver fix recommendations.</li>
                <li><strong>Send alerts</strong> -- notify you when tracked store scores change significantly (paid plans only).</li>
                <li><strong>Improve scoring</strong> -- analyze anonymized scan data to refine our scoring algorithms and benchmark reports.</li>
                <li><strong>Communicate</strong> -- send transactional emails (account verification, password resets, billing receipts) and occasional product updates.</li>
              </ul>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-slate-900 mt-8 mb-3">3. Third-Party Services</h2>
              <p>We use the following third-party services to operate MCPLens:</p>
              <ul className="list-disc pl-6 space-y-1 mt-2">
                <li><strong>Stripe</strong> -- payment processing. Stripe&apos;s privacy policy applies to payment data.</li>
                <li><strong>MongoDB Atlas</strong> -- database hosting for scan results and account data.</li>
                <li><strong>Resend</strong> -- transactional email delivery.</li>
                <li><strong>Fly.io</strong> -- application hosting and infrastructure.</li>
                <li><strong>Google Gemini API</strong> -- AI quality assessment and buyer agent simulation. Anonymized product catalog data (no personal data) is sent for analysis. Google's AI terms and privacy policies apply.</li>
              </ul>
              <p className="mt-2">
                We do not sell, rent, or share your personal data with third parties for their marketing purposes.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-slate-900 mt-8 mb-3">4. Data Retention</h2>
              <ul className="list-disc pl-6 space-y-1 mt-2">
                <li><strong>Scan results</strong> for free-tier scans are retained for 90 days. Paid plan scan results are retained while the subscription is active plus 30 days after cancellation.</li>
                <li><strong>Raw product catalog data</strong> retrieved during scans is used only for the duration of the scan and AI analysis, then discarded. Only scores, findings, and AI-generated summaries are stored.</li>
                <li><strong>Account data</strong> (email, preferences, team memberships) is retained while your account is active and deleted upon request.</li>
                <li><strong>Lead emails</strong> (submitted to unlock fixes without an account) are retained for up to 12 months, then purged.</li>
              </ul>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-slate-900 mt-8 mb-3">5. Your Rights</h2>
              <p>You have the right to:</p>
              <ul className="list-disc pl-6 space-y-1 mt-2">
                <li><strong>Access</strong> -- request a copy of all personal data we hold about you.</li>
                <li><strong>Delete</strong> -- request deletion of your account and associated personal data.</li>
                <li><strong>Export</strong> -- download your scan results and account data in a machine-readable format.</li>
                <li><strong>Correct</strong> -- update inaccurate personal information via your account settings.</li>
                <li><strong>Withdraw consent</strong> -- unsubscribe from non-transactional emails at any time.</li>
              </ul>
              <p className="mt-2">
                To exercise these rights, email us at{' '}
                <a href="mailto:hello@mcplens.dev" className="text-blue-600 hover:text-blue-700 underline">
                  hello@mcplens.dev
                </a>.
                We will respond within 30 days.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-slate-900 mt-8 mb-3">6. Cookies</h2>
              <p>
                MCPLens uses minimal cookies. We use a session authentication cookie to keep
                you signed in. We do not use tracking cookies, advertising cookies, or
                third-party analytics cookies unless explicitly added in the future, at which
                point this policy will be updated.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-slate-900 mt-8 mb-3">7. Store Owner Data Rights</h2>
              <p>
                MCPLens scans publicly accessible MCP endpoints in the same manner as AI buyer
                agents (e.g., ChatGPT, Perplexity). If you are the owner of a store that has
                been scanned:
              </p>
              <ul className="list-disc pl-6 space-y-1 mt-2">
                <li><strong>Data removal</strong> — you may request removal of all scan data associated with your domain at any time.</li>
                <li><strong>Opt-out</strong> — we will honor any standard opt-out mechanisms (e.g., robots.txt directives for MCP endpoints) as they become available.</li>
                <li><strong>Store claim</strong> — you may claim ownership of your store on MCPLens to manage scan data visibility and access enhanced reporting.</li>
              </ul>
              <p className="mt-2">
                To request data removal or claim your store, email{' '}
                <a href="mailto:hello@mcplens.dev" className="text-blue-600 hover:text-blue-700 underline">
                  hello@mcplens.dev
                </a>{' '}
                with your domain name and proof of ownership. We will respond within 30 days.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-slate-900 mt-8 mb-3">8. GDPR Compliance</h2>
              <p>For users in the European Economic Area (EEA):</p>
              <ul className="list-disc pl-6 space-y-1 mt-2">
                <li><strong>Free tier</strong> -- our legal basis for processing is legitimate interest (providing the scan service you requested).</li>
                <li><strong>Paid plans</strong> -- our legal basis for processing is contract performance (delivering the service you purchased).</li>
                <li><strong>Marketing emails</strong> -- sent only with your consent, which you can withdraw at any time.</li>
              </ul>
              <p className="mt-2">
                If you believe we have not adequately addressed your data protection concerns,
                you have the right to lodge a complaint with your local supervisory authority.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-slate-900 mt-8 mb-3">9. Changes to This Policy</h2>
              <p>
                We may update this Privacy Policy from time to time. Material changes will be
                communicated via email or a prominent notice on the Service. The "Last updated"
                date at the top of this page indicates when the policy was last revised.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-slate-900 mt-8 mb-3">10. Contact</h2>
              <p>
                If you have questions about this Privacy Policy or your data, please contact us at{' '}
                <a href="mailto:hello@mcplens.dev" className="text-blue-600 hover:text-blue-700 underline">
                  hello@mcplens.dev
                </a>.
              </p>
            </section>
          </div>
        </div>
      </main>

      {/* Footer */}
      <footer className="border-t border-slate-200 px-6 py-6 mt-12 bg-white">
        <div className="max-w-3xl mx-auto flex flex-wrap items-center justify-center gap-5 text-sm text-slate-400">
          <span>&copy; {new Date().getFullYear()} MCPLens</span>
          <Link to="/terms" className="hover:text-slate-900 transition-colors">Terms</Link>
          <Link to="/privacy" className="hover:text-slate-900 transition-colors">Privacy</Link>
        </div>
      </footer>
    </div>
  );
}
